### ISSUE TITLE
Docker(twic add cert issue)

### ISSUE THREAD

**Issue by githubadmi** [kassisol/hbm#4] opened 2017-06-10 08:29 UTC
Hi, 
I have to setup docker. For that i have to setup "HBM,TSA,TWIC" for users authentication on docker commands. I have setup TSA server, Docker host, AD.
Docker host:-
packaged installed:  docker-engine-1.12.6-1.el7.centos.x86_64,hbm-0.2.2-1.el7.centos.x86_64,twic-0.1.0-1.el7.centos.x86_64,

TSA server : - 

[root@workernode2 ~]# tsa info
Certificate Authority:
 Type: root
 Expire: 2027-05-30
 Country: INDIA
 State: HR
 Locality: Gurgoan
 Organization: Example
 Organizational Unit: IT department Certificate Authority
 Common Name: IT department Root CA
 E-mail: admin@example.com
API:
 FQDN: workernode2.example.com
 Bind Address: 0.0.0.0
 Bind Port: 443
Auth Type: ldap
Certificates: 1
 Valid: 1
 Expired: 0
 Revoked: 0
Server Version: 0.1.1
Storage Driver: sqlite
Logging Driver: standard
TSA Root Dir: /var/lib/tsa

[root@workernode2 ~]# tsa auth ls
KEY                    VALUE
auth_type              ldap
auth_host              ad1.example.com
auth_port              3269
auth_tls               true
auth_bind_username     admin@example.com
auth_attr_members      memberOf
auth_bind_password     secret
auth_search_base_user  ou=containers,dc=example,dc=com
auth_search_filter     (&(objectCategory=containers)(cn=%s))
auth_group_admin       cn=dockeradmin,ou=containers,ou=admindocker,dc=example,dc=com
auth_group_user        cn=docker1,ou=containers,ou=admindocker,dc=example,dc=com
********************************************************************************************************
Getting error while generation twic certificate. on client node as well as docker host, below are error message.

[docker1@workernode1 ~]$ twic cert add tsa1
TSA URL : https://workernode2.example.com
Username : admin (Admin user and credential)
Password : ******
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6b076c]

goroutine 1 [running]:
github.com/kassisol/twic/vendor/github.com/juliengk/stack/client.(*Request).Do(0xc4201a17c0, 0xa24446, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kassisol/twic/vendor/github.com/juliengk/stack/client/client.go:132 +0x74c
github.com/kassisol/twic/vendor/github.com/juliengk/stack/client.(*Request).Get(0xc4201a17c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/kassisol/twic/vendor/github.com/juliengk/stack/client/client.go:145 +0x95
github.com/kassisol/twic/vendor/github.com/kassisol/tsa/client.(*Config).GetDirectory(0xc4201ab180, 0x1f, 0xc4201ab180)
        /go/src/github.com/kassisol/twic/vendor/github.com/kassisol/tsa/client/client.go:42 +0x106
github.com/kassisol/twic/cli/command/cert.runAdd(0xc420077200, 0xc42018f6d0, 0x1, 0x1)
        /go/src/github.com/kassisol/twic/cli/command/cert/add.go:144 +0x60c
github.com/kassisol/twic/vendor/github.com/spf13/cobra.(*Command).execute(0xc420077200, 0xc42018f690, 0x1, 0x1, 0xc420077200, 0xc42018f690)
        /go/src/github.com/kassisol/twic/vendor/github.com/spf13/cobra/command.go:648 +0x231
github.com/kassisol/twic/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420076b40, 0xc420076b40, 0xc420076b40, 0xc420076b40)
        /go/src/github.com/kassisol/twic/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/kassisol/twic/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420076b40, 0xc4200001a0, 0xc4200001a0)
        /go/src/github.com/kassisol/twic/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
        /go/src/github.com/kassisol/twic/main.go:42 +0x2f

Please help me fix it. Thank you in advance

**Comment by githubadmi** [comment] 2017-06-10 08:30
please help me to fix it

**Comment by juliengk** [comment] 2017-06-10 09:50
Hi there,

The issue is not related to this HBM plugin! Can you close this one and open it in TWIC project.

Thank you

**Closed** 2017-06-10 10:46 UTC
